version: "3.8"
services:
  stock_be:
    image: frederickyapiter/be-app:latest
    ports:
      - "5000:5000"
    container_name: stock_be

  stock_fe:
    image: frederickyapiter/fe-app:latest
    environment:
      - REACT_APP_BACKEND=http://stock_be:5000/api/items
    ports:
      - "3000:3000"
    container_name: stock_fe
    depends_on:
      - stock_be


